# Generated by Django 6.1.2

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_documento", models.CharField(max_length=30)),
                ("documento", models.CharField(max_length=30)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(max_length=20)),
                ("fecha", models.DateField()),
                ("asistio", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-fecha", "apellidos", "nombres"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo_documento", "documento"),
                        name="unique_registro_asistencia_documento",
                    )
                ],
            },
        ),
    ]
